name: platform_video_converter
description: "A new Flutter package project."
version: 0.0.1
homepage: https://github.com/koji-1009/platform_video_converter
topics:
  - video
platforms:
  android:
  ios:
  macos:
  web:

environment:
  sdk: ^3.10.0
  flutter: ">=3.38.0"

dependencies:
  flutter:
    sdk: flutter
  jni: ^0.15.2
  ffi: ^2.1.4
  objective_c: ^9.2.2
  web: ^1.0.0
  cross_file: ^0.3.5+1

dev_dependencies:
  test: ^1.28.0
  flutter_lints: ^6.0.0
  ffigen: ^20.1.1
  jnigen: ^0.15.0
